// GENERATED by src/export_web.py, do not edit by hand.
// rerun run_pipeline.py to pick up new or renamed mris in saves/
import S0_MARKERS from "./data/T1/markers.json";
import S0_MC from "url:./data/T1/montecarlo.json";
import S1_MARKERS from "./data/T2/markers.json";
import S1_MC from "url:./data/T2/montecarlo.json";
import S2_MARKERS from "./data/T3/markers.json";
import S2_MC from "url:./data/T3/montecarlo.json";
import S3_MARKERS from "./data/T4/markers.json";
import S3_MC from "url:./data/T4/montecarlo.json";
import S4_MARKERS from "./data/T5/markers.json";
import S4_MC from "url:./data/T5/montecarlo.json";
import S5_MARKERS from "./data/T6/markers.json";
import S5_MC from "url:./data/T6/montecarlo.json";

export const DATASETS = {
  "T1": {
    label: "T1",
    scalpURL: new URL("./data/T1/scalp.ply", import.meta.url),
    coilURL: new URL("./data/T1/coil.ply", import.meta.url),
    markers: S0_MARKERS,
    monteCarloURL: S0_MC,
  },
  "T2": {
    label: "T2 (defaced)",
    scalpURL: new URL("./data/T2/scalp.ply", import.meta.url),
    coilURL: new URL("./data/T2/coil.ply", import.meta.url),
    markers: S1_MARKERS,
    monteCarloURL: S1_MC,
  },
  "T3": {
    label: "T3 (defaced)",
    scalpURL: new URL("./data/T3/scalp.ply", import.meta.url),
    coilURL: new URL("./data/T3/coil.ply", import.meta.url),
    markers: S2_MARKERS,
    monteCarloURL: S2_MC,
  },
  "T4": {
    label: "T4 (defaced)",
    scalpURL: new URL("./data/T4/scalp.ply", import.meta.url),
    coilURL: new URL("./data/T4/coil.ply", import.meta.url),
    markers: S3_MARKERS,
    monteCarloURL: S3_MC,
  },
  "T5": {
    label: "T5 (defaced)",
    scalpURL: new URL("./data/T5/scalp.ply", import.meta.url),
    coilURL: new URL("./data/T5/coil.ply", import.meta.url),
    markers: S4_MARKERS,
    monteCarloURL: S4_MC,
  },
  "T6": {
    label: "T6 (defaced)",
    scalpURL: new URL("./data/T6/scalp.ply", import.meta.url),
    coilURL: new URL("./data/T6/coil.ply", import.meta.url),
    markers: S5_MARKERS,
    monteCarloURL: S5_MC,
  },
};

export const AIM1 = null;
