# dump a scene out for the three.js viewer, ply meshes plus a small json. the
# coil is already placed in RAS so the viewer just loads it as is
import json
from pathlib import Path

import numpy as np


def export_web(scene, out_dir):
    """Write the meshes and markers.json for one subject."""

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # all meshes already in RAS mm
    scene.scalp.save(str(out_dir / "scalp.ply"))
    scene.coil.save(str(out_dir / "coil.ply"))
    if scene.brain is not None:
        scene.brain.save(str(out_dir / "brain.ply"))

    payload = {
        "subject": scene.name,
        "space": "RAS_mm",
        "targets": [_marker_json(t) for t in scene.targets],
        "landmarks": [_marker_json(m) for m in scene.landmarks],
        # threshold, defaced flag and so on, so the viewer can say what it is showing
        "qc": scene.qc,
    }

    with open(out_dir / "markers.json", "w") as f:
        json.dump(payload, f, indent=2)

    return out_dir


def _marker_json(m):
    return {
        "name": m.name,
        "label": m.label,
        "color": m.color,
        "position": _vec(m.contact),
        "normal": _vec(m.normal),
    }


def _vec(v):
    return [round(float(x), 3) for x in np.asarray(v)]


def write_registry(data_dir, registry_path):
    """Regenerate datasetRegistry.js from whatever subject folders actually exist.

    parcel needs static imports, so the viewer cannot read the folder at runtime.
    the pipeline writes this file instead, which means the dropdown always matches
    the mris that have actually been processed. rename a file in saves, rerun the
    pipeline, and the dropdown follows.
    """

    data_dir = Path(data_dir)
    registry_path = Path(registry_path)

    subjects = sorted(
        d.name for d in data_dir.iterdir()
        if d.is_dir() and (d / "markers.json").exists()
    )
    if not subjects:
        raise ValueError(f"no processed subjects found under {data_dir}")

    imports, entries = [], []
    for i, name in enumerate(subjects):
        # the folder name is whatever the mri was called, so it can be anything.
        # keep it verbatim as the label and the key, and use a safe made up
        # identifier for the import binding
        var = f"S{i}"
        imports.append(f'import {var}_MARKERS from "./data/{name}/markers.json";')
        imports.append(f'import {var}_MC from "./data/{name}/montecarlo.json";')

        # a wiped face is the scan, not a bug, so say so where the subject is picked
        with open(data_dir / name / "markers.json") as f:
            qc = json.load(f).get("qc", {})
        label = f"{name} (defaced)" if qc.get("defaced") else name

        entries.append(
            f'  {json.dumps(name)}: {{\n'
            f'    label: {json.dumps(label)},\n'
            f'    scalpURL: new URL("./data/{name}/scalp.ply", import.meta.url),\n'
            f'    brainURL: new URL("./data/{name}/brain.ply", import.meta.url),\n'
            f'    coilURL: new URL("./data/{name}/coil.ply", import.meta.url),\n'
            f'    markers: {var}_MARKERS,\n'
            f'    monteCarlo: {var}_MC,\n'
            f'  }},'
        )

    text = (
        "// GENERATED by src/export_web.py, do not edit by hand.\n"
        "// rerun run_pipeline.py to pick up new or renamed mris in saves/\n"
        + "\n".join(imports)
        + "\n\nexport const DATASETS = {\n"
        + "\n".join(entries)
        + "\n};\n"
    )
    registry_path.write_text(text, encoding="utf-8")
    return registry_path, subjects
