# dump a scene out for the three.js viewer, ply meshes plus a small json. the
# coil is already placed in RAS so the viewer just loads it as is
import json
from pathlib import Path

import numpy as np
import pyvista as pv

# the scalp the browser gets. the full mesh is ~430k triangles and 8 to 11 MB, which
# is slow to pull into an embedded page. 60k triangles sits within 0.07 mm of the
# full surface (checked with pyvista compute_implicit_distance on T1) at about 1.5 MB.
# the targets, the monte carlo and the previews all still use the full mesh
WEB_SCALP_FACES = 60_000


def web_mesh(surf, faces=WEB_SCALP_FACES):
    """A lighter copy of a triangle mesh for the browser, point data dropped."""

    # polygons only, then triangles. a defaced scan can leave stray line cells and
    # the odd polygon where the wipe was capped, and decimation takes triangles only
    mesh = pv.PolyData(surf.points, surf.faces).triangulate().clean()
    if mesh.n_cells > faces:
        mesh = mesh.decimate(1.0 - faces / mesh.n_cells)
    mesh = mesh.copy()
    # the viewer computes its own normals, shipping them only doubles the file
    mesh.clear_data()
    return mesh


def export_web(scene, out_dir):
    """Write the meshes and markers.json for one subject."""

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # all meshes already in RAS mm
    web_mesh(scene.scalp).save(str(out_dir / "scalp.ply"))
    scene.coil.save(str(out_dir / "coil.ply"))

    payload = {
        "subject": scene.name,
        "space": "RAS_mm",
        "targets": [_marker_json(t) for t in scene.targets],
        "landmarks": [_marker_json(m) for m in scene.landmarks],
        # threshold, defaced flag and so on, so the viewer can say what it is showing
        "qc": scene.qc,
    }

    with open(out_dir / "markers.json", "w") as f:
        json.dump(payload, f, indent=2)

    return out_dir


def _marker_json(m):
    return {
        "name": m.name,
        "label": m.label,
        "color": m.color,
        "optional": bool(getattr(m, "optional", False)),
        "position": _vec(m.contact),
        "normal": _vec(m.normal),
    }


def _vec(v):
    return [round(float(x), 3) for x in np.asarray(v)]


def write_registry(data_dir, registry_path):
    """Regenerate datasetRegistry.js from whatever subject folders actually exist.

    parcel needs static imports, so the viewer cannot read the folder at runtime.
    the pipeline writes this file instead, which means the dropdown always matches
    the mris that have actually been processed. rename a file in saves, rerun the
    pipeline, and the dropdown follows.

    the monte carlo json is half a MB per subject, so it goes in as a url: asset
    and the viewer fetches only the subject on screen, rather than every subject
    riding in the script bundle. the aim 1 statistics (analysis/aim1_stats.py)
    come in when that file exists, and as null until then
    """

    data_dir = Path(data_dir)
    registry_path = Path(registry_path)

    subjects = sorted(
        d.name for d in data_dir.iterdir()
        if d.is_dir() and (d / "markers.json").exists()
    )
    if not subjects:
        raise ValueError(f"no processed subjects found under {data_dir}")

    imports = []
    if (data_dir / "aim1_stats.json").exists():
        imports.append('import AIM1_DATA from "./data/aim1_stats.json";')
    entries = []
    for i, name in enumerate(subjects):
        # the folder name is whatever the mri was called, so it can be anything.
        # keep it verbatim as the label and the key, and use a safe made up
        # identifier for the import binding
        var = f"S{i}"
        imports.append(f'import {var}_MARKERS from "./data/{name}/markers.json";')
        imports.append(f'import {var}_MC from "url:./data/{name}/montecarlo.json";')

        # a wiped face is the scan, not a bug, so say so where the subject is picked
        with open(data_dir / name / "markers.json") as f:
            qc = json.load(f).get("qc", {})
        label = f"{name} (defaced)" if qc.get("defaced") else name

        entries.append(
            f'  {json.dumps(name)}: {{\n'
            f'    label: {json.dumps(label)},\n'
            f'    scalpURL: new URL("./data/{name}/scalp.ply", import.meta.url),\n'
            f'    coilURL: new URL("./data/{name}/coil.ply", import.meta.url),\n'
            f'    markers: {var}_MARKERS,\n'
            f'    monteCarloURL: {var}_MC,\n'
            f'  }},'
        )

    aim1 = "AIM1_DATA" if (data_dir / "aim1_stats.json").exists() else "null"
    text = (
        "// GENERATED by src/export_web.py, do not edit by hand.\n"
        "// rerun run_pipeline.py to pick up new or renamed mris in saves/\n"
        + "\n".join(imports)
        + "\n\nexport const DATASETS = {\n"
        + "\n".join(entries)
        + "\n};\n\n"
        # the real aim 1 numbers, written by analysis/aim1_stats.py off brainsight
        + f"export const AIM1 = {aim1};\n"
    )
    registry_path.write_text(text, encoding="utf-8")
    return registry_path, subjects

